<a href="https://colab.research.google.com/github/aylenalderete/Machine-Learning-with-Python/blob/main/PandasNumpyPlatzi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Dimensiones
scalar: dim = 0 Un solo dato o valor

vector: dim = 1 Listas de Python

matriz: dim = 2 Hoja de cálculo

tensor: dim > 3 Series de tiempo o Imágenes

In [3]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [4]:
vector = np.array([1,2,3])
print(vector)
scalar.ndim

[1 2 3]


0

In [5]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [9]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]], [[12,42,43],[54,65,36],[27,68,69]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[12 42 43]
  [54 65 36]
  [27 68 69]]]


3

# Agregar o eliminar dimensiones

In [10]:
vector = np.array([1,2,3], ndmin=10) 
#Numero de dimensiones igual a 10
print(vector)
scalar.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


0

In [11]:
#Expandir una sola dimensión en sus ejes:
expand = np.expand_dims(np.array([1,2,3]), axis=0)

#Axis igual a 0 significa filas, si pongo 1 significa columnas

print(expand)
expand.ndim

[[1 2 3]]


2

In [12]:
#Eliminar
print(vector, vector.ndim)

vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


# Creando arrays

In [16]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.linspace(0, 10 , 10)
#permite generar una arrary definiendo un inicio, un final y cuantas divisiones tendrá.

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [24]:
#También podemos crear una matriz con una diagonal de 1 y el resto de 9.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.random.rand()
#generar números aleatorios.

0.4293120076730068

In [28]:
np.random.rand(4)
#generar matrices aleatorias.

array([0.0020477 , 0.78511637, 0.17316739, 0.26250967])

In [29]:
np.random.rand(4,4)

array([[5.74501629e-01, 9.41963112e-02, 6.55421647e-04, 6.18029661e-01],
       [7.20865190e-02, 1.74470166e-01, 4.69583888e-01, 6.00717564e-01],
       [4.38510853e-01, 2.87870636e-01, 8.75086580e-01, 8.82196085e-01],
       [3.26233853e-01, 2.87487237e-01, 9.05240902e-01, 6.84694471e-01]])

In [30]:
np.random.randint(1,15)
# números enteros entre el 1 y 14

8

In [35]:
np.random.randint(1,15, (3,3))
#de 1 a 15, pero con una estructura definida de 3 por 3

array([[ 3,  9, 11],
       [ 1, 13, 13],
       [ 6, 14, 13]])